name       : cryptomator
version    : 1.5.0
release    : 3
source     :
    - https://github.com/cryptomator/cryptomator/archive/1.5.0.tar.gz : fa0e9b9c71f8fbfef070b7b0604feebf94c1b6e439eae6f2d2bf7bb7ff58f7f3
license    : MIT
component  : security.crypto
summary    : Client-side encryption of your files in the cloud
description: |
    Multi-platform transparent client-side encryption of your files in the cloud
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-11
build      : |
    export MAVEN_OPTS="-Dmaven.repo.local=.m2"
    export JAVA_HOME=/usr/lib64/openjdk-11
    cd main
    mvn -Prelease package
install    : |
    install -dm00644 $installdir/usr/share/cryptomator/libs/
    install -dm00755 $installdir/usr/bin/

    install -Dm00644 main/buildkit/target/libs/* main/buildkit/target/linux-libs/* $installdir/usr/share/cryptomator/libs/
    install -Dm00755 main/buildkit/target/launcher-linux.sh $installdir/usr/share/cryptomator/cryptomator
    ln -s /usr/share/cryptomator/cryptomator $installdir/usr/bin/cryptomator

    install -Dm00644 cryptomator.png $installdir/usr/share/pixmaps/cryptomator.png
    install -Dm00644 $pkgfiles/cryptomator.desktop $installdir/usr/share/applications/cryptomator.desktop

    sed -i "1r $pkgfiles/java-shim.txt" $installdir/usr/share/cryptomator/cryptomator
    sed -i "s:libs:/usr/share/cryptomator/libs:" $installdir/usr/share/cryptomator/cryptomator
