name       : cryptomator
version    : 1.3.5
release    : 2
source     :
    - https://github.com/cryptomator/cryptomator/archive/1.3.5.tar.gz : 6123104bf4dc9d711d2e57098a2cb691a556ec85b439ac0363b82092acaedf01
license    : MIT
component  : security.crypto
summary    : Client-side encryption of your files in the cloud
description: |
    Multi-platform transparent client-side encryption of your files in the cloud
networking : yes
builddeps  :
    - apache-maven
    - openjfx-8
rundeps    :
    - openjfx-8
build      : |
    export MAVEN_OPTS='-Dmaven.repo.local=.m2'
    cd main
    mvn -Prelease package
install    : |
    install -Dm00644 main/uber-jar/target/Cryptomator-*.jar $installdir/usr/share/cryptomator/cryptomator.jar
    install -Dm00755 $pkgfiles/cryptomator.sh $installdir/usr/bin/cryptomator
    install -Dm00644 main/ant-kit/src/main/resources/package/linux/Cryptomator.png $installdir/usr/share/pixmaps/cryptomator.png
    install -Dm00644 $pkgfiles/cryptomator.desktop $installdir/usr/share/applications/cryptomator.desktop
