name       : cryptomator
version    : 1.3.3
release    : 1
source     :
    - https://github.com/cryptomator/cryptomator/archive/1.3.3.tar.gz : b87d13b83d19e50e73e043163bb3917324a8641aaa768b099d24c712d423d0a1
license    : MIT
component  : security.crypto
summary    : Client-side encryption of your files in the cloud
description: |
    Multi-platform transparent client-side encryption of your files in the cloud
networking : yes
builddeps  :
    - apache-maven
    - openjfx-8
rundeps    :
    - openjfx-8
build      : |
    cd main
    mvn clean install -Prelease -Dmaven.repo.local=$workdir/repo
install    : |
    install -Dm644 main/uber-jar/target/Cryptomator-*.jar $installdir/usr/share/java/cryptomator/cryptomator.jar
    install -Dm755 $pkgfiles/cryptomator.sh $installdir/usr/bin/cryptomator
    install -Dm644 main/ant-kit/src/main/resources/package/linux/Cryptomator.png $installdir/usr/share/pixmaps/cryptomator.png
    install -Dm644 $pkgfiles/cryptomator.desktop $installdir/usr/share/applications/cryptomator.desktop
